version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassw0rdButWrongStored
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql-data:

